name: On push main
on:
  push:
    branches:
      - main
jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version
        # https://github.com/anothrNick/github-tag-action?tab=readme-ov-file#workflow
        # To do a major version bump then use '#major` in the merge commit message
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
