name: On pr main

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test-go:
    name: Lint test go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.61
      - run: go test ./...
